app/config/tests.js, app/core-components/navigation/tests/NavigationBar.test.js, app/modules/content-items/components/content-item-display/tests/PlainTextContentItemDisplay.test.js, app/modules/content-items/components/tests/EditorBlock.test.js, app/modules/content-items/components/tests/EditorRoot.test.js, app/modules/topics/components/tests/Editor.test.js, app/modules/topics/components/tests/List.test.js, app/modules/topics/components/tests/Preview.test.js, app/pages/components/tests/EditorPage.test.js, app/pages/components/tests/HomePage.test.js, app/pages/components/tests/LibraryPage.test.js, app/pages/components/tests/NewTopicPage.test.js, app/pages/components/tests/NotFoundPage.test.js, app/pages/components/tests/TopicsPage.test.js
Added tests config file with dummy props so these don't have to be copy/pasted into every React component test; updated existing tests to use config file instead of copy/pasted props.
=> Refactor component tests dummy props

.travis.yml
Significantly speeds up Travis build by preventing jest from spawning more workers than Travis can handle.
=> Fix travis build speed

app/assets/stylesheets/custom/ows_slide.less, app/core-components/slides/Slide.js, app/core-components/slides/Slides.js, app/core-components/slides/tests/Slide.test.js, app/core-components/slides/tests/Slides.test.js, app/lib/content-item-split/dummyData.js, app/lib/content-item-split/index.js, app/lib/content-item-split/tests/index.test.js, app/modules/content-items/dummyData.js, app/pages/components/TempSlideTestPage.js
- Add `<Slides>`: multiple slides overview
- Basic slide splitting
- New slide for every top-level heading
- New slide for every subheading + duplicated top-level heading
I could not get Flow to cooperate on the `lib/content-item-split/index` file. Anyone any suggestions?
=> Feature slide splitting

app/lib/api/apis/users.js, app/modules/feed/components/Event.js, app/modules/users/saga/api/tests/users.test.js, app/modules/users/saga/api/users.js
Kinda solves #75. Couldn't find a way to invalidate users only once, right after signing in, so now it fetches the email of a user if it's missing.
Issues:
- backend only returns email of authenticated user
=> fetch user's email if it is missing in Event

.babelrc, package.json, webpack.config.js, yarn.lock
Removed `babel-plugin-transform-runtime` and replaced it with `babel-polyfill`, because a) the polyfill is recommended for apps, and b) transform-runtime was causing errors when using `export * from './file'` syntax.
=> Fix babel / webpack config

.babelrc, .eslintrc, .eslintrc.js, app/core-components/gravatar/tests/Gravatar.test.js, app/core-components/inline-markdown/tests/index.test.js, app/lib/api/tests/ApiRequest.test.js, app/lib/api/tests/asyncFetch.test.js, app/lib/content-item-split/tests/index.test.js, app/lib/generate-random-string/tests/index.test.js, app/lib/localStorage/tests/index.test.js, app/modules/api/tests/selectors.test.js, app/modules/contentItems/components/HtmlDisplay/index.test.js, app/modules/feed/tests/selectors.test.js, app/modules/history/tests/selectors.test.js, app/modules/topics/tests/actions.test.js, package.json, yarn.lock
Added `eslint-plugin-jest` in order to better check jest tests for errors / code smells & fixed errors. One test now fails (previously false negative); temporarily commented it out, will fix when cleaning up that part of the code. See https://trello.com/c/T52TGjv8
=> Eslint jest

.eslintrc.js, package.json, yarn.lock
Installed eslint-plugin-promise and configured it to enforce using async/await syntax for asynchronous functionality. See https://trello.com/c/T52TGjv8
=> Eslint-promise

.eslintrc.js, app/modules/apiRequestsStatus/index.js, app/modules/authentication/actionTypes.js, app/modules/authentication/actions.js, app/modules/authentication/components/AccountMenu.js, app/modules/authentication/components/forms/ConfirmForm.js, app/modules/authentication/components/forms/ResetForm.js, app/modules/authentication/components/forms/SigninForm.js, app/modules/authentication/components/forms/SignupForm.js, app/modules/authentication/index.js, app/modules/authentication/model.js, app/modules/authentication/selectors.js, app/modules/contentItems/components/EditableDisplay/.eslintrc.js, app/modules/contentItems/components/HtmlDisplay/.eslintrc.js, app/modules/contentItems/index.js, app/modules/contentItems/lib/find/.eslintrc.js, app/modules/feed/index.js, app/modules/history/index.js, app/modules/sidebars/index.js, app/modules/topics/index.js, app/modules/users/index.js, app/pages/ProfilePage.js, app/routes.js, app/store/modulesReducer.js, app/store/rootSaga.js, app/store/tests/modulesReducer.test.js, app/store/tests/rootSaga.test.js, app/types/state.js, jest.config.js
Fixed the 2 major sources of circular dependencies:
- `modulesReducer`, `rootSaga` and `types/state` now directly import files without first importing the entire modules; these are the only places where the `import/no-internal-modules` may be disabled.
- Temporarily replaced all instances of the `User` type in `modules/authentication` by `any`. `modules/authentication` needs to be refactored to contain a userId instead of the entire user, since in a normalized data structure all users belong under `modules.users`. See next pull request.
Enabled `import/no-cycle` rule in `.eslintrc` to prevent future circular dependencies from occurring; added `.eslintrc` override files which disable the rule for certain subfolders (contentItems `EditableDisplay`, `HtmlDisplay` and `lib/find`) where the …
=> Fix circular dependencies

app/components/ApplicationPage/AuthPage/ConfirmEmailPage/index.test.js, app/components/ApplicationPage/UserPage/SignoutPage/index.test.js, app/components/ConditionalWrapper/index.test.js, app/components/FlashMessages/index.test.js, app/components/PageWrapper/NavigationBar/AccountMenu/index.test.js, app/components/SidebarsPageWrapper/index.test.js, app/forms/UserForm/index.test.js, app/lib/testResources/DummyProviders.js, app/lib/testResources/index.js, app/modules/apiRequestsStatus/components/ApiDimmer.test.js, app/modules/contentItems/components/EditableDisplay/index.test.js, app/modules/contentItems/components/EditableDisplay/typesToComponentsMap/Root.test.js, app/modules/platform/components/AuthWrapper/index.test.js, app/modules/platform/components/ResendConfirmationEmailCard/index.test.js, app/modules/platform/components/ResetPasswordCard/index.test.js, app/modules/platform/components/Sidebars/index.test.js, app/modules/platform/components/SidebarsMenu/SidebarsMenuItem/index.test.js, app/modules/platform/components/SigninCard/index.test.js, app/modules/platform/components/SignupCard/index.test.js, app/modules/platform/components/UnauthWrapper/index.test.js
Added `DummyProviders` component, which makes it much easier to test components that have been `mount`ed. Updated existing tests to use `DummyProviders` instead of manually creating all necessary providers.
=> Feature dummy providers

app/api/confirmation/post.test.js, app/api/confirmation/postEmail.test.js, app/api/notifications/getAll.test.js, app/api/password/postEmail.test.js, app/api/token/delete.test.js, app/api/token/postSignin.test.js, app/api/topics/delete.test.js, app/api/topics/get.test.js, app/api/topics/getAllByUserId.test.js, app/api/topics/getContent.test.js, app/api/topics/patchContent.test.js, app/api/topics/post.test.js, app/api/users/get.test.js, app/api/users/post.test.js, app/errors/apiErrors/index.js, app/errors/apiErrors/subclasses/UnexpectedEmptyResponseError.js, app/errors/apiErrors/subclasses/UnexpectedEmptyResponseError.test.js, app/errors/apiErrors/subclasses/UnexpectedHttpResponseError.js, app/errors/apiErrors/subclasses/UnexpectedHttpResponseError.test.js, app/lib/ApiRequest/ApiRequest/fetchApiResponseData/index.js, app/lib/ApiRequest/ApiRequest/fetchApiResponseData/index.test.js, app/lib/ApiRequest/types.js, app/modules/platform/saga/api/apiPostSigninToTokenAndGetUserAuth.js, app/modules/platform/saga/api/apiPostSigninToTokenAndGetUserAuth.test.js, app/modules/users/saga/api/apiGet.js, app/modules/users/saga/api/apiGet.test.js
Fixed the `SyntaxError: Unexpected end of JSON input` error on requests that return no response body. This was caused by not adequately checking if there is a proper body before trying to parse it to JSON.
The `mockResponseOnce` call everywhere was also changed not to use `null` as response body. In real conditions, `response.json()` or `response.text()` will always return something (a promise). Tests should mimic this behaviour by returning something (an empty string) instead of `null`.
=> Fix unexpected JSON

app/components/ApplicationPage/AuthPage/SSOCallbackPage/index.js, app/components/ApplicationPage/AuthPage/SSOCallbackPage/index.test.js, app/components/ApplicationPage/AuthPage/index.js, app/config/routes.js, app/i18n/en/platform.js, app/modules/platform/actionTypes/taskSaga.js, app/modules/platform/actions/taskSaga/index.js, app/modules/platform/actions/taskSaga/signinSSO.js, app/modules/platform/actions/taskSaga/signinSSO.test.js, app/modules/platform/components/SigninCard/index.js, app/modules/platform/saga/task/index.js, app/modules/platform/saga/task/signinSSO.js, app/modules/platform/saga/task/signinSSO.test.js
Enable SSO (Single Sign On) for the platform, using three providers:
- Google
- Facebook
- UGent CAS
Users can use these providers to sign in to the platform without having to sign up. Caveat: the user is identified by its email, so signing in with a UGent CAS account will necessarily use a UGent email address.
This PR adds links to the sign in page, and a callback page that processes the server response.
@Dromin The sign in links will not work locally, because they redirect to `/oauth/whatever`, which is routed by the web server in production. http://owsdev.ugent.be has a working instance.
=> Enable Single Sign On

app/api/endpoints.js, app/api/feedItems/getAll.js, app/api/feedItems/getAll.test.js, app/api/feedItems/index.js, app/api/index.js, app/api/notifications/index.js, app/config/api.js, app/modules/feed/saga/api/feedItems.js, app/modules/feed/saga/api/index.js, app/modules/feed/saga/api/tests/feedItems.test.js, app/modules/feed/saga/api/tests/index.test.js
- Replace all references to `notifications` by `feedItems` in actions, sagas, components.
- Rename Feed.Event to Feed.FeedItem
- Rename all references to `events` by `feedItems`
- Bump API version
[Backlog item](https://trello.com/c/ftQImfKx/67-rename-notifications-to-feed-items)
=> Rename notifications to feed

app/config/api.js, app/config/api.js.erb, readme.md, webpack.config.js
- Revert API endpoint change. 
- Allow specifying an API_URL using an environment variable, to prevent having to change the `api.js` file all the time. Usage:
```
$ API_URL=http://localhost:3000/api yarn run dev-server
```
=> Fix API config

app/api/topics/get.js, app/api/topics/get.test.js, app/modules/topics/saga/api/apiGet.js, app/modules/topics/saga/api/apiGet.test.js
Add a `token` argument to topics `apiGet` saga. Fixes #185.
=> Allow authenticated topics apiGet calls

app/api/topics/get.test.js, app/api/topics/getAllByUserId.js, app/api/topics/getAllByUserId.test.js, app/api/topics/getContent.js, app/api/topics/getContent.test.js, app/modules/contentItems/saga/api/apiGetAllByTopicId.js, app/modules/contentItems/saga/api/apiGetAllByTopicId.test.js
Same bug as #186, but this time the `getContent` and `getAllByUserId` are also included.
This closes #185 (again).
=> Allow authenticated api.topics.getContent and .getAllByUserId calls

.eslintrc.js, app/forms/EmailAndPasswordForm/index.js, app/forms/EmailForm/index.js, app/forms/ResetPasswordForm/index.js, app/forms/TopicForm/index.js, app/forms/UserForm/index.js, app/modules/topics/components/Editor/index.js, package.json, yarn.lock
Added eslint-plugin-babel to enable checking for experimental JS features which have been enabled by babel; fixed newly detected errors.
=> Fix missing eslint check for class properties

app/config/api.js, app/modules/feedItems/saga/api/apiGetAll.js, app/modules/feedItems/saga/api/apiGetAll.test.js
:warning: Merge PR #201 first.
Rename feedItem `eventType` to `feedItemType` in API parser.
[Documentation](https://openwebslides.github.io/documentation/#api-v10)
[Trello](https://trello.com/c/iX1mPK5F/152-rename-feeditem-eventtype-into-feeditemtype)
=> Rename feedItem eventType to feedItemType

app/config/api.js, webpack.config.js
Updated `webpack-config.js` and `api.js` so that setting the `API_URL` now goes through the webpack `--env` flag instead of `process.env`. (This is necessary because the old way doesn't work with `jest-dev-server`. Putting this in a separate pull request so @floriandejonckheere is sure to see the change.) 
Previous way of passing `API_URL`: 
~`$ API_URL=http://localhost:3000/api yarn run dev-server`~
New way of passing `API_URL`:
`$ yarn run dev-server --env.API_URL=http://localhost:3000/api`
=> Fix API_URL manual setup

app/modules/users/saga/task/update.test.js
Users/UPDATE saga test was missing a provider for the FETCH action, which caused a timeout during testing:
```
console.warn node_modules/redux-saga-test-plan/lib/expectSaga/index.js:309
[WARNING]: Saga exceeded async timeout of 250ms
```
=> Fix broken users/UPDATE saga test

app/api/pullRequests/index.js, app/api/pullRequests/patch.js, app/api/pullRequests/patch.test.js, app/config/api.js, app/lib/testResources/dummyPullRequestData.js, app/modules/pullRequests/actionTypes/apiSaga.js, app/modules/pullRequests/actionTypes/taskSaga.js, app/modules/pullRequests/actions/apiSaga/apiPatch.js, app/modules/pullRequests/actions/apiSaga/apiPatch.test.js, app/modules/pullRequests/actions/apiSaga/index.js, app/modules/pullRequests/actions/taskSaga/accept.js, app/modules/pullRequests/actions/taskSaga/accept.test.js, app/modules/pullRequests/actions/taskSaga/index.js, app/modules/pullRequests/actions/taskSaga/reject.js, app/modules/pullRequests/actions/taskSaga/reject.test.js, app/modules/pullRequests/model/index.js, app/modules/pullRequests/saga/api/apiGet.js, app/modules/pullRequests/saga/api/apiGet.test.js, app/modules/pullRequests/saga/api/apiPatch.js, app/modules/pullRequests/saga/api/apiPatch.test.js, app/modules/pullRequests/saga/api/index.js, app/modules/pullRequests/saga/task/accept.js, app/modules/pullRequests/saga/task/accept.test.js, app/modules/pullRequests/saga/task/index.js, app/modules/pullRequests/saga/task/reject.js, app/modules/pullRequests/saga/task/reject.test.js
- Add API call configuration, sagas and actions to update a pull request. Updating in this context means accepting/rejecting (the actions are named accordingly)
- Add `feedback` to pull request
- Add missing states to pull request, appearing in API v11
- Update API requirement to v11
- [API v11 changelog](https://openwebslides.github.io/documentation/#api-v11)
- [Accept a PR](https://openwebslides.github.io/documentation/#accept-a-pull-request)
- [Reject a PR](https://openwebslides.github.io/documentation/#accept-a-pull-request)
=> Pull request API calls

app/config/url.js, webpack.config.js
Push the configuration of `API_URL` and `APP_URL` to dev and prod webpack environments. This fixes (assumably) UglifyJS mangling references to global variables that we still need in prod.
=> Fix prod environment

app/modules/contentItems/actionTypes/reducer.js, app/modules/contentItems/actions/reducer/convertInState.js, app/modules/contentItems/actions/reducer/convertInState.test.js, app/modules/contentItems/actions/reducer/index.js, app/modules/contentItems/reducer/convertInState.js, app/modules/contentItems/reducer/convertInState.test.js, app/modules/contentItems/reducer/index.js, app/modules/contentItems/saga/task/edit.js, app/modules/contentItems/saga/task/edit.test.js
Paragraphs can now be converted into headings by inserting '# ' (note the space) at the start of the text field.
(Note: headings cannot currently be converted back into paragraphs. However, this limitation can be worked around by inserting a new paragraph and cutting/pasting the heading's text.)
=> Feature: converting paragraphs into headings
