.travis.yml, package.json, readme.md, yarn.lock
- Travis integration
- Coveralls integration
=> Travis integration

.eslintrc, app/core-components/inline-markdown/tests/index.test.js, app/core-components/navigation/tests/NavigationBar.test.js, app/core-components/slides/content-item-html-display/tests/index.test.js, app/core-components/slides/content-item-html-display/types/tests/Heading.test.js, app/core-components/slides/content-item-html-display/types/tests/Paragraph.test.js, app/core-components/slides/content-item-html-display/types/tests/Root.test.js, app/core-components/slides/tests/Slide.test.js, app/lib/generate-random-string/tests/index.test.js, app/modules/content-items/components/content-item-display/tests/PlainTextContentItemDisplay.test.js, app/modules/content-items/components/helpers/tests/EditableTextContent.test.js, app/modules/content-items/components/tests/EditorBlock.test.js, app/modules/content-items/components/tests/EditorRoot.test.js, app/modules/content-items/lib/denormalize/tests/index.test.js, app/modules/content-items/tests/selectors.test.js, app/modules/topics/components/tests/Editor.test.js, app/modules/topics/components/tests/TopicCard.test.js, app/modules/topics/model.js, app/modules/topics/tests/actions.test.js, app/modules/topics/tests/reducer.test.js, app/modules/topics/tests/selectors.test.js, app/modules/users/model.js, app/pages/components/tests/EditorPage.test.js, app/pages/components/tests/HomePage.test.js, app/pages/components/tests/LibraryPage.test.js, app/pages/components/tests/NewTopicPage.test.js, app/pages/components/tests/NotFoundPage.test.js, app/pages/components/tests/TempSlideTestPage.test.js
=> Fix eslintrc: disable certain rules for tests

app/store/errorReducer.js
Print error messages to error console for developer inspection.
=> ErrorReducer: print errors to console

app/modules/authentication/components/AccountMenu.js, app/modules/authentication/reducer.js, app/modules/feed-items/components/FeedItem.js, app/modules/feed-items/components/tests/FeedItem.test.js, app/modules/topics/components/index.js, app/modules/users/components/ProfileCard.js, app/pages/components/HomePage.js, app/pages/components/LibraryPage.js, app/pages/components/NewTopicPage.js, app/pages/components/ProfilePage.js, app/pages/components/tests/ProfilePage.test.js
NOTE: Contains code from #53 . Merge that one first
=> Link auth with library

app/lib/api/ApiRequest.js, app/lib/api/api.js.erb, app/lib/api/constants.js, app/lib/api/tests/ApiRequest.test.js, public/index.html
Enable environment config variables in production
=> Deployment configuration

app/assets/stylesheets/site/elements/button.overrides, app/assets/stylesheets/site/globals/site.variables, app/assets/stylesheets/site/modules/dropdown.overrides, app/assets/stylesheets/site/modules/modal.overrides, app/assets/stylesheets/site/modules/modal.variables, app/assets/stylesheets/site/views/card.overrides, app/assets/stylesheets/site/views/card.variables, app/assets/stylesheets/site/views/feed.overrides, app/assets/stylesheets/site/views/feed.variables, app/modules/authentication/components/ConfirmCard.js, app/modules/authentication/components/ResetCard.js, app/modules/authentication/components/SigninCard.js, app/modules/authentication/components/SignupCard.js, app/modules/feed/components/Event.js, app/modules/topics/components/TopicCard.js, app/pages/components/LibraryPage.js
Style changes in navbar, / and /library
=> Misc styling

app/i18n/en/namespaces/common.js, app/modules/api/components/ApiDimmer.js, app/modules/api/components/tests/ApiDimmer.test.js, app/modules/authentication/components/SigninCard.js
~**:warning: Approve and merge #96 first**~
- Content is now optional
- Allow specifying multiple requests to watch
This closes #105.
=> Enhance ApiDimmer

app/errors/ApiError.js, app/errors/api-errors/ForbiddenError.js, app/errors/api-errors/ServerError.js, app/errors/api-errors/UnauthorizedError.js, app/errors/api-errors/ValidationError.js, app/lib/api/asyncFetch.js, app/lib/api/errors.js, app/lib/api/tests/asyncFetch.test.js
=> Refactor asyncfetch errors

app/core-components/slides/VoicePlayerToggle.js, app/core-components/slides/tests/VoicePlayerToggle.test.js, app/lib/react-voice-components/VoicePlayer.js, app/pages/components/TempSlideTestPage.js, flow-typed/npm/react-color_v2.x.x.js, jest.config.js, package.json, yarn.lock
Changes copied from #74, since commit history was too complicated to be able to rebase in a reasonable amount of time. Closes #74.
=> Feature: slide voice player

app/config/api.js, app/core-components/flash/tests/FlashMessages.test.js, app/core-components/logo/index.js, app/core-components/logo/tests/index.test.js, app/core-components/navigation/NavigationBar.js, app/core-components/navigation/tests/NavigationBar.test.js, app/core-components/slides/tests/Slides.test.js, app/lib/api/ApiRequest.js, app/lib/api/constants.js, app/lib/api/tests/ApiRequest.test.js, app/lib/localStorage/index.js, app/lib/localStorage/tests/index.test.js, app/modules/authentication/actionTypes.js, app/modules/authentication/actions.js, app/modules/authentication/tests/actions.test.js, app/modules/feed/actionTypes.js, app/modules/feed/actions.js, app/modules/topics/actionTypes.js, app/modules/topics/actions.js, app/modules/topics/reducer.js, app/modules/topics/saga/api/get.js, app/modules/topics/saga/api/index.js, app/modules/topics/saga/task/index.js, app/modules/topics/tests/actions.test.js, app/modules/topics/tests/reducer.test.js, app/modules/users/actionTypes.js, app/setupTests.js
:warning: Merge #112 first
Fix various issues.
This closes #78, #101 and #97.
=> Issue closing wednesday

app/modules/history/actionTypes.js, app/modules/history/actions.js, app/modules/history/components/History.js, app/modules/history/components/index.js, app/modules/history/index.js, app/modules/history/model.js, app/modules/history/reducer.js, app/modules/history/saga/api/index.js, app/modules/history/saga/index.js, app/modules/history/saga/task/index.js, app/modules/history/saga/task/redirect.js, app/modules/history/saga/task/tests/redirect.test.js, app/modules/history/selectors.js, app/modules/history/tests/actions.test.js, app/modules/history/tests/reducer.test.js, app/modules/history/tests/selectors.test.js, app/pages/Page.js, app/pages/routes.js, app/store/modulesReducer.js, app/store/rootSaga.js, app/types/state.js
:warning: Merge #113 first
Add new routing mechanism. Whenever the user has to be redirected, the developer needs to dispatch a `redirect` action now.
=> Feature history

app/core-components/slides/Slide.js, app/core-components/slides/Slides.js, app/core-components/slides/tests/Slide.test.js, app/lib/content-item-split/index.js, app/lib/content-item-split/tests/index.test.js
:warning: Merge #117 first
Render a rootContentItem on every slide.
This closes #115.
=> Issue 115 render root content item

package.json, webpack.config.js, yarn.lock
Add a robots.txt file that disallows API routes.
=> Add robots.txt webpack generator

package.json, webpack.config.js, yarn.lock
Let webpack automatically generate favicons in different sizes and formats, and add a tag to the generated HTML.
=> Generate favicon tags

app/api/topics/post.js, app/api/topics/post.test.js, app/modules/topics/actionTypes/apiSaga.js, app/modules/topics/actions/apiSaga/apiPost.js, app/modules/topics/actions/apiSaga/apiPost.test.js, app/modules/topics/saga/api/apiGet.js, app/modules/topics/saga/api/apiGet.test.js, app/modules/topics/saga/api/apiPost.js, app/modules/topics/saga/api/apiPost.test.js, app/modules/topics/saga/task/create.js, app/modules/topics/saga/task/create.test.js, app/modules/users/saga/task/addTopic.js
Still has errors which can't be fixed until https://trello.com/c/rhXvSd5H has been fixed; main purpose is to get to a point where I can properly test these fixes in the first place.
=> Update to api v4

app/modules/contentItems/components/EditableDisplay/index.js, app/modules/contentItems/components/EditableDisplay/index.test.js, app/modules/contentItems/lib/index.js, app/modules/contentItems/lib/isEmpty/index.js, app/modules/contentItems/lib/isEmpty/index.test.js, app/modules/contentItems/saga/task/edit.js, app/modules/contentItems/saga/task/edit.test.js, app/modules/contentItems/saga/task/toggleEditing.js, app/modules/contentItems/saga/task/toggleEditing.test.js
See https://trello.com/c/QXc33pWb
=> Fix ObjectNotFoundError when pressing enter on an empty contentItem.

app/i18n/en/topics.js, app/lib/testResources/dummyTopicData.js, app/modules/contentItems/components/EditableDisplay/index.js, app/modules/contentItems/components/EditableDisplay/index.test.js, app/modules/topics/actionTypes/reducer.js, app/modules/topics/actionTypes/taskSaga.js, app/modules/topics/actions/reducer/index.js, app/modules/topics/actions/reducer/setDirtyInState.js, app/modules/topics/actions/reducer/setDirtyInState.test.js, app/modules/topics/actions/taskSaga/discard.js, app/modules/topics/actions/taskSaga/discard.test.js, app/modules/topics/actions/taskSaga/index.js, app/modules/topics/components/Editor/index.js, app/modules/topics/components/Editor/index.test.js, app/modules/topics/model/index.js, app/modules/topics/reducer/index.js, app/modules/topics/reducer/setDirtyInState.js, app/modules/topics/reducer/setDirtyInState.test.js, app/modules/topics/saga/api/apiGet.js, app/modules/topics/saga/api/apiGet.test.js, app/modules/topics/saga/task/discard.js, app/modules/topics/saga/task/discard.test.js, app/modules/topics/saga/task/index.js, app/modules/topics/saga/task/patchWithContent.js, app/modules/topics/saga/task/patchWithContent.test.js
Add a dirty bit on topic, to keep track whether or not the topic was modified in the editor.
=> Topics dirty bit

app/api/topics/patchContent.js, app/api/topics/patchContent.test.js, app/components/ApplicationPage/TopicPage/ViewerPage/index.test.js, app/config/api.js, app/forms/CommitForm/index.js, app/forms/CommitForm/index.test.js, app/i18n/en/topics.js, app/modules/contentItems/actionTypes/apiSaga.js, app/modules/contentItems/actions/apiSaga/apiPatchAllByTopicIdAndRoot.js, app/modules/contentItems/actions/apiSaga/apiPatchAllByTopicIdAndRoot.test.js, app/modules/contentItems/saga/api/apiPatchAllByTopicIdAndRoot.js, app/modules/contentItems/saga/api/apiPatchAllByTopicIdAndRoot.test.js, app/modules/topics/actionTypes/taskSaga.js, app/modules/topics/actions/taskSaga/patchWithContent.js, app/modules/topics/actions/taskSaga/patchWithContent.test.js, app/modules/topics/components/Editor/index.js, app/modules/topics/components/Editor/index.test.js, app/modules/topics/saga/task/create.js, app/modules/topics/saga/task/create.test.js, app/modules/topics/saga/task/patchWithContent.js, app/modules/topics/saga/task/patchWithContent.test.js
Adds a required commit message when saving a topic. Additionally, implements the dirty topic logic in the editor (prevent leaving when dirty, ...).
=> Commit message

CHANGELOG.md, app/config/version.js
Release platform v2.
See [changelog](https://github.com/OpenWebslides/openwebslides-frontend/blob/a78f09c930ea11622faa71145edc01cea7b1574a/CHANGELOG.md)
=> Bump version to 2.0.0

app/components/EditableTextContent/index.js, app/components/EditableTextContent/index.test.js, app/modules/contentItems/actionTypes/taskSaga.js, app/modules/contentItems/actions/taskSaga/add.js, app/modules/contentItems/actions/taskSaga/add.test.js, app/modules/contentItems/lib/convertContextToVerticalContext/index.js, app/modules/contentItems/model/context.js, app/modules/feedItems/components/Feed/FeedItem/index.js, app/modules/topics/components/TopicsList/index.js
See: 
- https://trello.com/c/lh7j0Yvs
- https://trello.com/c/MYeLZ057
- https://trello.com/c/zZIqTEkk
- https://trello.com/c/RL1X7Dst
=> Fix: multiple smaller bugs

readme.md
Fix command using an environment variable not being an environment variable anymore.
=> Fix incorrect yarn command in readme.md

app/modules/contentItems/actionTypes/taskSaga.js, app/modules/contentItems/actions/taskSaga/generatePlaceholder.js, app/modules/contentItems/actions/taskSaga/generatePlaceholder.test.js, app/modules/contentItems/actions/taskSaga/index.js, app/modules/contentItems/saga/task/generatePlaceholder.js, app/modules/contentItems/saga/task/generatePlaceholder.test.js, app/modules/contentItems/saga/task/generateRoot.js, app/modules/contentItems/saga/task/generateRoot.test.js, app/modules/contentItems/saga/task/index.js, app/modules/contentItems/saga/task/remove.js, app/modules/contentItems/saga/task/remove.test.js
Auto-generate a placeholder when the last contentItem in a topic is deleted.
=> Fix: delete last content item bug
